name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: thebarshablog/github-readme-youtube-cards@main
        with:
          channel_id: UCNTA-kDhvz0LSGpx9-K0cpA
